DOP-4904: Remove docs/ from v1.17
mongodb/mongo-php-library pull request #1369
Opened 2024-08-11 22:33 UTC by i80and

This is a companion PR to https://github.com/mongodb/docs-php-library/pull/97.

2024-08-12 08:38 UTC, GromNaN requested changes
From this version, you need to remove `<file>docs/examples</file>` from phpcs.xml
https://github.com/mongodb/mongo-php-library/blob/28aabbe0e437e4ad9840165e608cc13696a5a5bd/phpcs.xml.dist#L14

Is there a plan to enable style checks in the new doc repository?

2024-08-12 08:50 UTC, GromNaN requested changes

2024-08-12 08:50 UTC, GromNaN commented on docs/examples/encryption/create_data_key.php
Some tests need to be moved as the this files are removed.

https://github.com/mongodb/mongo-php-library/blob/28aabbe0e437e4ad9840165e608cc13696a5a5bd/tests/ExamplesTest.php#L302

Failing test:
https://github.com/mongodb/mongo-php-library/actions/runs/10343254255/job/28627151546?pr=1369#step:9:224

2024-09-04 08:07 UTC, alcaeus commented
Closing as we won't be removing docs from old branches.

2024-09-04 08:07 UTC, closed without merging